version: '{build}'
clone_depth: 10
skip_tags: true

os: Windows Server 2012
services:
  - mssql2012sp1
  - mssql2014
environment:
  global:
    DB: mssql
  matrix:
    - MSSQL_INSTANCE: SQL2012SP1
      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - MSSQL_INSTANCE: SQL2012SP1
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - MSSQL_INSTANCE: SQL2014
      JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - MSSQL_INSTANCE: SQL2014
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: .\script\appveyor-setup-mssql.ps1 $env:MSSQL_INSTANCE
  - ps: .\script\appveyor-install-maven.ps1 3.3.9
  - cmd: mvn --version
  - cmd: java -version

before_build:
  - sqlcmd -U sa -P Password12! -S .\%MSSQL_INSTANCE% -Q "CREATE DATABASE spring_data_jdbc_repository_test"
  - sqlcmd -U sa -P Password12! -S .\%MSSQL_INSTANCE% -d spring_data_jdbc_repository_test -i src\test\resources\schema_mssql.sql
build_script:
  - mvn clean install -DskipTests=true
test_script:
  - mvn verify -B
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
